plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	// 將Java專案當為web的套件
	implementation 'org.springframework.boot:spring-boot-starter-web'
	
	// 右鍵 > Gradle > Refresh Gradle Project 來進行更新下載
	// spring data jpa(版本號可省略，依據 id 'org.springframework.boot' 的 version 注入)
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	// mysql connector: mysql 驅動
	implementation 'com.mysql:mysql-connector-j'
	
	// security
    implementation 'org.springframework.boot:spring-boot-starter-security'
	
	// 資料驗證
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	
	// 程式碼修改後儲存會自動重啟 Application(不一定成功)
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
