spring.application.name=quizList260727

spring.datasource.url=jdbc:mysql://localhost:3306/quiz_list_260727?serverTimezone=Asia/Taipei&useSSL=false&rewriteBatchedStatements=true
spring.datasource.username=root
spring.datasource.password=jk911220
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

# Generate a Base64 secret:
# openssl rand -base64 32
jwt.secret=eOdL1jqMn7bV1US+OuvKWqMVCbotTvQDuP/qQ07VRmU=
# Access token expiration (30 minutes)
jwt.expiration=1800000
